name: "Start app"
description: "Starts the app on the server. First - checks if it is authorized. If not - creates an issue with instructions."


inputs:
  registry_username:
    required: true
    description: "Registry  username"
  registry_password:
    required: true
    description: "Registry password"
  image:
    required: true
    description: "Image name"
  base-image:
    required: true
    description: "Base image name"

runs:

  using: composite

  steps:

    - name: Set up Docker Buildx
      id: buildx_setup
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      id: docker_login
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Build and push
      id: build-base
      shell: bash
      run: |
        command="docker buildx build --progress plain --output type=registry --tag ${{ inputs.base-image }} --push --file docker/base.dockerfile ."
        echo $command
        docker pull ${{ inputs.base-image }} || $command 

    - name: Build and push
      id: build-app
      shell: bash
      run: |
        docker buildx build --progress plain --output type=registry --tag ${{ inputs.image }} --push --file docker/app.dockerfile .
