name: "Start app"
description: "Starts the app on the server. First - checks if it is authorized. If not - creates an issue with instructions."


inputs:
  server-host:
    required: true
    description: "Connection string to postgres database server"
  server-username:
    required: true
  server-key:
    required: true
  server-port:
    required: true
  auth-code:
    required: false
    description: "Authorization code"
  pat:
    required: true
  image:
    required: true

runs:

  using: composite

  steps:

    - name: start app
      id: start-app
      uses: appleboy/ssh-action@v1.0.0
      with:
        host:  ${{ inputs.server-host }}
        username: ${{ inputs.server-username }}
        key: ${{ inputs.server-key }}
        port: ${{ inputs.server-port }}
        script: |
          export IMAGE=${{ inputs.image }}
          # we have to stop everything because tdlib cannot run concurrent clients
          docker-compose stop
          
          if [ -z "${{ inputs.auth-code }}" ]; then
            echo "App is already authorized"
          else
            phone=$(docker-compose logs teleforward | grep 'auth code is needed for' | tail -1 | awk '{print $NF}')
            timeout --signal SIGKILL 10s docker-compose run --rm teleforward init $phone:${{ inputs.auth-code }}
          fi
          docker-compose up -d

    - name: create an issue
      uses: dacbd/create-issue-action@v1.2.1
      if: steps.start_app.outcome != 'success'
      with:
        token: ${{ inputs.pat }}
        title: Authorization needed
        body: |
          # Telegram authorization is needed
          Looks like you have not authorized the app.
          You can check it manually on server and close this issue.
          If you do know that app needs to be authorized please, enter the authorization code in the comment below.
          Put your comment as `/auth code=XXXXXX`.




