on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: antonioantuan/teleforward:latest

#      - name: create an issue
#        uses: dacbd/create-issue-action@main
#        with:
#          token: ${{ secrets.PAT }}
#          title: Authorization needed
#          body: |
#            # Telegram authorization is needed
#            Please, enter the authorization code in the comment below.
#            Put your comment as `/auth code=XXXXXX`.
