name: auth-command

permissions:
  issues: write

env:
  code: ''
  IMAGE: ${{ vars.IMAGE_NAME }}:latest

on:
  workflow_dispatch:
    inputs:
      code:
        type: string
        default: ''
        required: true
        description: 'Authorization code'

jobs:
  prepare:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: auth and start
        id: auth-and-start
        uses: ./.github/actions/start-app
        with:
          server-host: ${{ secrets.SERVER_HOST }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-key: ${{ secrets.SERVER_KEY }}
          server-port: ${{ secrets.SERVER_PORT }}
          auth-code: ${{ github.event.inputs.code }}
          image: ${{ env.IMAGE }}
          server_workdir: ${{ secrets.SERVER_APP_PATH }}
